### ISSUE TITLE
Support exact-pi 0.4

### ISSUE THREAD

**Issue by DanBurton** [bjornbm/dimensional#103]
See: https://github.com/fpco/stackage/issues/957

**Comment by dmcclean** [comment]
Will do.

**Comment by dmcclean** [comment]
Reopening this until it hits hackage.

**Comment by dmcclean** [comment]
Fixed in `dimensional-1.0.1.0`, which just hit hackage.

**Comment by DanBurton** [comment]
Awesome, thanks!

**Comment by dmcclean** [comment]
Sure thing.

Dan, are there some rules of stackage written that we should be aware of or that you could summarize? I still don't quite understand what it's all about, but I certainly don't want to accidentally make work for you guys by not knowing the ground rules.

**Comment by DanBurton** [comment]
Sure. Check out the [Package Author guidelines](https://github.com/fpco/stackage#package-author-guidelines).

The general idea of Stackage is that we are constantly running builds and looking for reasonably new versions of all packages that are still compatible with the whole ecosystem without breaking stuff. The way we judge if a new package version is suitable for inclusion in stackage is:
- do its dependency constraints work with the current state of stackage?
- did it build?
- did it pass its test suite?
- did its haddocks turn out ok?
- did it break anything that depends on it?

So, if your package depends on old versions of things, then we'll start pestering you to get compatible with the latest version. This is pretty routine, so don't feel bad if we ping you. The sooner everyone is able to support the new version of a package, the sooner that new version makes it into stackage.

I'm happy to answer any further questions or elaborate some more if you wish.

**Comment by dmcclean** [comment]
Awesome, thanks Dan.

I figured that since I had made the commits on both sides of this issue (the `exact-pi` ones and the `dimensional` ones) that I was missing something.

Now I won't push new versions of `exact-pi` to hackage without being ready with a version of `dimensional` that builds against it, at least within a day or two of lag time for doing all the release steps.

**Comment by DanBurton** [comment]
:+1: sounds good to me.
