### ISSUE TITLE
Arithmetic for dynamic quantities

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#104]
It would be nice to have arithmetic operations for `AnyQuantity`.

Multiplication and division are easy (given that pretty much everybody is ok with `error` for division by zero). Addition and subtraction should probably be `AnyQuantity -> AnyQuantity -> Maybe AnyQuantity`?

Interestingly that would mean that `AnyQuantity` only has a multiplicative candidate for a `Monoid` instance, whereas `Quantity d a` only has an additive one.

**Comment by dmcclean** [comment]
Added the `Monoid` instance in 143c4e0c36b0d38100dc3f6f7bc6a59adae1c5e6

**Comment by dmcclean** [comment]
Perhaps `instance Num a => Num (Maybe (AnyQuantity a))` would be a good path to explore?

**Comment by bjornbm** [comment]
Couldn't `instance Num a => Num (AnyQuantity a)` do? If the dimensions are is bad you would get `Nothing` in the end when trying to promote.

`instance Num a => Num (Maybe (AnyQuantity a))` would collide with, e.g., a hypothetical `instance Num a => Num (Maybe a)`.

**Comment by dmcclean** [comment]
Good idea. Right now there is a `HasDimnsion (AnyQuantity a)` instance, though. What would that `dimension :: AnyQuantity a -> Dimension'` function do?

**Comment by bjornbm** [comment]
Hmm, good question. Is that instance used and/or needed anywhere? And could a custom function with a Maybe be used in those cases?

**Comment by dmcclean** [comment]
I'm anticipating that the use is something like this (code against hypothetical parsing API, leaving out a billion imports and probably some details):

```
askQuantity :: UnitMap a -> Proxy d -> String -> IO (Maybe (Quantity d a))
askQuantity units d prompt = do
  putStrLn prompt
  input <- getLine
  -- if input means quit then return nothing
  let q = parseOnly (quantity units) input
  case q of
    Left err = do
                 putStrLn $ "Couldn't parse your input: " ++ err
                 askQuantity units d prompt
    Right q' = do
                 if (dimension q' == dimension d)
                   then return . promoteQuantity $ q' -- guaranteed to return a Just
                   else if (dimension q' == dOne)
                     then askWhichUnitsTheyMeantSinceTheyClearlyForgot units d q'
                     else do
                       putStrLn $ "Expected a " ++ show (dimension d) ++ " but got a " ++ show (dimension q') ++ ". Try again."
                       askQuantity units d prompt
```

A function that returns `Maybe Dimension'` is definitely a good option. It breaks the symmetry between `AnyQuantity` and `AnyUnit` because only the former will be actually guaranteed to be a unit of some dimension, though. Perhaps introducing a third type other than `Maybe (AnyQuantity a)` is the way to go, but in that case it needs a name.

Is there a realistic prospect of a `Num a => Num (Maybe a)` instance? It seems fairly clear what it would do, so perhaps there is. Or at least there might be a reasonable chance that some user has an orphan for it? See this thread and in particular this comment from Edward on it: https://www.reddit.com/r/haskell/comments/1yb4eq/newbie_question_num_instance_for_maybe_a/cfj95xj

**Comment by dmcclean** [comment]
The parser also needs arithmetic for dynamic units, including dynamic prefix application.

**Comment by dmcclean** [comment]
This is a lot heavier and involves a dependency, but `instance (Monad m) => Num (ExceptT QuantityError AnyQuantity)`? Or `instance Num (Either QuantityError AnyQuantity)`?

**Comment by dmcclean** [comment]
So after writing this, I think the viable options are:
1. Changing the semantics and representation of AnyQuantity and AnyUnit so that they don't necessarily represent a quantity or unit, but might instead just be nothing, ditching the `HasDimension` instances.
2. `instance Num a => Num (Maybe (AnyQuantity a))`
3. `newtype DynQuantity a = DynQuantity (Maybe (AnyQuantity a))` and `instance Num a => Num (DynQuantity a)`, living alongside `AnyQuantity`. Similarly for units.

Analysis:
2 is undesirable because there really is a sensible `instance Num a => Num (Maybe a)` instance, and it just isn't in base for whatever reason, but it might exist in projects as an orphan or might be added.

1 is undesirable because for serialization purposes I would like to retain having a type that represents something which is definitely a valid quantity, but simply of an statically unknown dimension, which is what `AnyQuantity` does now.

3 is fine as long as it's well documented. It doesn't clutter code with newtype wrappers because they only appear in a couple of lifting functions that are used to define all the math operations. It actually even makes client signatures a bit easier.

As long as there is documentation of the difference then I like 3.

I like it even better now that I just thought of:

```
class DynamicQuantity (q :: * -> *) where
  demoteQuantity :: Quantity d a -> q a
  promoteQuantity :: q a -> Maybe (Quantity d a)

instance DynamicQuantity AnyQuantity where
  -- existing demoteQuantity and promoteQuantity definitions, they already have the correct types

instance DynamicQuantity DynQuantity where
  demoteQuantity = DynQuantity . Just . demoteQuantity
  promoteQuantity (DynQuantity (Just x)) = promoteQuantity x
  promoteQuantity _                      = Nothing
```

(and a variation on the them for units). The nice thing about this is that it reduces namespace pollution/confusion of many similar names.

**Comment by dmcclean** [comment]
Damn, I built this all out and it is awesome, but because of an obscure issue with the `InstanceSigs` extension and how they interact with associated type families (like `Dimensional`) it doesn't build in GHC 7.8.

`demoteQuantity` actually needs a slightly different type from the one I gave above, namely:

```
class DynamicQuantity (q :: * -> *) where
  demoteQuantity :: (KnownDimension d) => Quantity d a -> q a
  promoteQuantity :: (KnownDimension d) => q a -> Maybe (Quantity d a)
```

Which would be OK, except that the implementation needs scoped type variables and the signatures to introduce them need `InstanceSigs` and wait a minute that might be a solution...
