### ISSUE TITLE
Reexport generalized (.) and id

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#124]
I propose changing `Numeric.Units.Dimensional.Prelude` to reexport the definitions of `(.)` and `id` from `Control.Category` instead of the ones from `Prelude`.

This is similar to e6b8ccbc11afb5385b9eec6065184a762350ed31, and done for a similar reason. The motivating example is that my work-in-progress `Coordinates` module does all kinds of stuff with composing projections between coordinate systems, but importing it along with the dimensional prelude is wordy because you need to have the generalized `(.)` in scope and not the functions-only one from `Prelude`.

**Comment by bjornbm** [comment]
No objections!
