### ISSUE TITLE
Readme and changelog markdown is garbled on hackage

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#126]
But why is it garbled? I compared to packages where it is shown clearly and nothing jumped out at me. Maybe a line endings issue?

**Comment by dmcclean** [comment]
We seem to have the same line endings, and the same style convention, in ours as Edward has in his `linear` package, but his changelog is formatted nicely and ours is garbled. I'm pretty baffled at this point. He does use a `.markdown` extension instead of a `.md` extension, but clearly hackage is making at least some effort to render our changelog as markdown, it's just going off the rails, because it does convert some of our `*`s into `<li>`s.

**Comment by dmcclean** [comment]
`pipes-attoparsec` has a `.md` changelog that works, but uses `#` style headers.

**Comment by dmcclean** [comment]
Nothing jumps out from reading the `hackage-server` [source](https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Pages/Package.hs).

**Comment by dmcclean** [comment]
It is the line endings after all, I didn't check it correctly. Filed an issue with hackage to request they be more tolerant so it doesn't trip up others. Preparing a patch.

**Comment by bjornbm** [comment]
:+1:
