### ISSUE TITLE
Consider switching build to use stack?

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#127]
Benefits and approaches discussed here: https://www.fpcomplete.com/blog/2015/12/stack-travis

**Comment by bjornbm** [comment]
Having played a tiny bit with stack I am for this. All I had to do was a `stack init` (I used the nightly resolver which seemed appropriate for development??) in the repo to generate the stack.yaml file. Largely thanks to your efforts to restructure the repo I suspect. :+1:

**Comment by dmcclean** [comment]
I've only just gotten started with it too, but it does seem pretty nice (once I got past a few windows issues). Also they are supposedly working on automatic hackage documentation uploads, which will be nice because the current state is a pain when the automatic builds on the hackage server aren't working.

**Comment by dmcclean** [comment]
See the results of https://travis-ci.org/dmcclean/dimensional/builds/102417341

It looks like doctest isn't running the C preprocessor (or isn't running it properly?) on GHC 7.8's LTS version of doctest?
