### ISSUE TITLE
Hour angles

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#128]
Should we introduce a definition like:

```
hourAngle :: (Floating a) => Unit 'NonMetric DPlaneAngle a
hourAngle = mkUnitR someName 15 $ degree
```

I wrote `someName` because I can't determine if the UCUM defines this unit, because their website is down (and has been for at least a couple of days).

Similarly for minutes and seconds.

This would allow using the same machinery for #82 to deal with things like https://github.com/bjornbm/astro/blob/265916aa35b0269702e15eed879ec211d3cd4517/Astro/Util.hs#L56-L63.

**Comment by bjornbm** [comment]
I have no objection in principle. Choosing good names for the subunits may prove tricky. From [Wikipedia](https://en.wikipedia.org/wiki/Angle#Units):

> #### Hour angle (n = 24)
> 
> The astronomical hour angle is 1/24 of a turn. Since this system is amenable to measuring objects that cycle once per day (such as the relative position of stars), the sexagesimal subunits are called minute of time and second of time.

"Minute of time" would cause confusion with the minute of dimension `DTime`. And I fear that e.g. "minute angle" (analogous to hour angle) could too easily be mistaken for minute of arc.

**Comment by dmcclean** [comment]
I think as you identified at the end of the #181 thread, perhaps the linked example is best modeled by constructing a `Time Double` and multiplying it by an angular velocity. (Here the angular velocity is a little strange because it is solar time and exact, but it still has the dimensions of angular velocity.)

In that case there might be little value to the unit, especially given the difficulty of naming its sub units.

I am therefore closing this issue. Anyone who disagrees, please feel free to comment.
