### ISSUE TITLE
Dimensional variant of logBase

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#129]
We have dimensionally-typed versions of all the functions in `Floating` except `logBase`.

Is there a reason why the following definition would be problematic?

```
logBase :: (Floating a) => Dimensionless a -> Dimensionless a -> Dimensionless a
logBase = liftQ2 (Prelude.logBase)
```

**Comment by bjornbm** [comment]
At the time I may have been reasoning that logBase is more likely to be done on numbers rather than physical quantities (dimensionless or otherwise) and therefore chose to not override the Prelude one. But I have no objections to your change if you feel it is more appropriate.

**Comment by dmcclean** [comment]
Interesting point. I think it's worth keeping for consistency.
