### ISSUE TITLE
Wrappers for isNan, isInfinite

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#134]
What is the recommended way of validating that the floating point quantities someone gave you are actual numbers?

If you are receiving them as `Double`s and using `*~` to add on the unit, it seems clear that you can easily do the validation yourself before the multiplication.

However, it also seems very convenient to use the `Binary` or `Storable` or `FromJSON` instances for, e.g., `Velocity Double` to build up serialization and deserialization functions for entire records at once. (This becomes even more useful with the forthcoming fixed point support.) If you do that, then the unit ascriptions become implicit and you never see the `Double` before it becomes a `Quantity Double`.

Would it make sense to add wrappers like `isInfiniteQuantity :: RealFloat a => Quantity d a -> Bool` to perform this sort of validation after deserialization?

**Comment by bjornbm** [comment]
This seems that it could be useful. It would also allows to sanity check results of calculations where not obviously pathological input quantities cause a Inf or NaN to occur.
