### ISSUE TITLE
Relax type of dimensionlessLength

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#141]
Since the beginning (see https://github.com/bjornbm/dimensional/blob/072047347b033863bb849354ecf4738793f9dabd/Numeric/Units/Dimensional/TF.lhs#L390-L391) we've had:

```
dimensionlessLength :: (Num a, Foldable f) => f (Dimensional v d a) -> Dimensionless a
```

I went to write an example use of this in the doctests and was surprised to find that I was using a more general type in my head and so my example didn't work.

Should we relax it to:

```
dimensionlessLength :: (Num a, Foldable f) => f b -> Dimensionless a
```

This would be a breaking change because `a` is less constrained in the result and so some uses of the existing type might become ambiguous.

**Comment by bjornbm** [comment]
I think we should.
