### ISSUE TITLE
Signum

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#151]
I'm working on some feature enhancements for the `atmos` package, in which it is useful for various reasons to use indicator functions derived from `Num`'s `signum` and subtraction instead of using the comparison operators from `Ord`.

Can we add `signum :: (Num a) => Quantity d a -> Dimensionless a` (with the obvious implementation) or is there some reason in principle why that is a bad idea?

We would still be respecting the (dimensionally-typed flavor of the) `x == signum x * abs x` identity.

**Comment by bjornbm** [comment]
Works for me. I think I didn't include it from day one because I wasn't certain what would be the desireable return type (`Dimensionless a` or maybe just `a`??). But I agree with satisfying the identity so please go ahead!
