### ISSUE TITLE
Add the gauss as a unit of magnetic flux density

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#156]
Are we allowing ourselves to add cgs esu units as units of the associated SI dimension?

**Comment by bjornbm** [comment]
No objection. I assume that by associated SI dimension you refer to _mass \* time^-2 \* current^-1_ as opposed to _length^(-1/2) \* mass^(1/2) \* time^-1_ which we cannot express.

**Comment by dmcclean** [comment]
Yes, that's what I meant, I just couldn't come up with a good way to explain it. Looking up what it was in the cgs basis would have been a good start. :)
