### ISSUE TITLE
Support for building with NoImplicitPrelude

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#168]
I want to have a `.ghci` file that sets the `:set -XNoImplicitPrelude` option (along with `:set -XNegativeLiterals`) as I almost always want this in a GHCI session using dimensional (to avoid ambiguous names with the arithmetic operators).

With the current state you can set this option after all the dimensional modules are loaded, but then if you modify some and reload you can (depending on which you modified) get errors. You can't have it set in your `.ghci` file or you will always get errors (because it changes how the dimensional modules are interpreted when they are loaded.

I propose making all our modules (almost all already do) work with `NoImplicitPrelude` on so that it will be possible to keep this setting in the `.ghci` file and streamline workflow. There's no user-facing impact because it only affects what we import, not what we export.

**Comment by bjornbm** [comment]
No problem at all with this. Are we OK with regard to NegativeLiterals? If I recall correctly results could be surprising sometimes, but nothing that couldn’t be fixed by adding parentheses.

**Comment by dmcclean** [comment]
I'm not sure. I haven't run into problems with the "obvious" ways of using it (mostly just `let x = -37 *~ meter`) but that might be because I almost never have literals embedded in larger expressions.

Either way, this change doesn't force anything on anyone with regard to `NegativeLiterals`, I was just mentioning as an aside that my `.ghci` file also does that and some other minor things.

**Comment by bjornbm** [comment]
OK. There are some cases to be aware of where whitespace becomes significant, or an expression evaluates differently (i.e., it NegativeLiterals does not only allow “more” syntax, but also changes the meaning of existing syntax. See http://flygdynamikern.blogspot.jp/2014/02/joy-and-caution-with-xnegativeliterals.html (including comments).

**Comment by dmcclean** [comment]
Valid points. Thanks for the heads up.
