### ISSUE TITLE
Dynamic polydimensional zero

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#170]
Before we release the revised API for `DynQuantity` and friends, I think we should change it up a bit.

A difficulty I ran into with `dimensional-parsers` (which is getting really good, by the way, and is ready for release as soon as dimensional 1.1 is, check out the test cases: https://github.com/dmcclean/dimensional-parsers/blob/master/tests/Test.hs) is that it would be nice to have a representation for poly-dimensional zero that can be promoted to zero of any quantity.

My primary anticipated use for `dimensional-parsers` is for configuration files. Adding support for polydimensional zero there would bring all the same benefits to the configuration file writers that `_0` brings to static users of `dimensional`.

See https://github.com/dmcclean/dimensional/tree/more-dynamic-zero for a take on how this might look.

**Comment by bjornbm** [comment]
Sounds like a good idea to me. Haven't look in detail at the more-dynamic-zero branch; any particular hairy part or impact to non-dynamic use/API I should look at, or it is under control?

The parser tests look good!

**Comment by dmcclean** [comment]
The only real impact is that it changes the (unpublished as yet) `HasDynamicDimension` class from

``` haskell
-- | Dimensional values, or those that are only possibly dimensional, inhabit this class,
-- which allows access to a term-level representation of their dimension.
class HasDynamicDimension a where
  -- | Gets the 'Dimension'' of a dynamic dimensional value, or 'Nothing' if it does not represent
  -- a dimensional value of any 'Dimension'.
  --
  -- A default implementation is available for types that are also in the `HasDimension` typeclass.
  dynamicDimension :: a -> Maybe Dimension'
  default dynamicDimension :: (HasDimension a) => a -> Maybe Dimension'
  dynamicDimension = Just . dimension
```

to

``` haskell
-- | Dimensional values, or those that are only possibly dimensional, inhabit this class,
-- which allows access to a term-level representation of their dimension.
class HasDynamicDimension a where
  -- | Gets the 'DynamicDimension of a dynamic dimensional value, which may be 'NoDimension' if it does not represent
  -- a dimensional value of any 'Dimension'.
  --
  -- A default implementation is available for types that are also in the `HasDimension` typeclass.
  dynamicDimension :: a -> DynamicDimension
  default dynamicDimension :: (HasDimension a) => a -> DynamicDimension
  dynamicDimension = SomeDimension . dimension
```

where

``` haskell
-- | The dimension of a dynamic value, which may not have any dimension at all.
data DynamicDimension = NoDimension -- ^ The value has no valid dimension.
                      | SomeDimension Dimension' -- ^ The value has the given dimension.
                      | AnyDimension -- ^ The value may be interpreted as having any dimension.
  deriving (Eq, Ord, Show)
```

Other than that, using `DynQuantity` is the same, you basically just use it through the `Num` interface and promote out to `Maybe (Quantity d a)` when you want the answer.

**Comment by dmcclean** [comment]
There is a marginally hairy part of the implementation of the two argument operations like `+` and `*` to make sure they properly handle `Zero`. Lifting the single-argument functions was still easy, because I just added an argument to the lifting function to control how they respond to a `Zero` argument, but for the two argument functions there are more complicated cases. I won't merge it before adding test cases for all they dynamic arithmetic.

**Comment by dmcclean** [comment]
https://github.com/dmcclean/dimensional/blob/more-dynamic-zero/src/Numeric/Units/Dimensional/Dynamic.hs#L142-L163

https://github.com/dmcclean/dimensional/blob/more-dynamic-zero/src/Numeric/Units/Dimensional/Dynamic.hs#L216-L228

**Comment by dmcclean** [comment]
`DynamicDimension` is `Levitated Dimension'` from the `lattices` package (https://hackage.haskell.org/package/lattices-1.5.0/docs/Algebra-Lattice-Levitated.html) but I think rolling our own is simpler.
