### ISSUE TITLE
Product

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#178]
We currently have `sum :: (Num a, Foldable f) => f (Quantity d a) -> Quantity d a`, but we reexport `product` from the prelude at `product :: (Num a, Foldable t) => t a -> a`.

Should we have `product :: (Num a, Foldable f) => f (Dimensionless a) -> Dimensionless a`? It seems we should for consistency, but it is a breaking change.

**Comment by bjornbm** [comment]
I needed and wrote this myself just recently. Perhaps we should add it.
