### ISSUE TITLE
Should `degree`, `arcminute`, `arcsecond` be Metric?

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional#180]
Should `degree`, `arcminute`, `arcsecond` be `Metric`? Currently:

    degree, arcminute, arcsecond :: Floating a => Unit 'NonMetric DPlaneAngle a

Wikipedia says:

> To express even smaller angles, standard SI prefixes can be employed; the milliarcsecond (mas) and microarcsecond (μas), for instance, are commonly used in astronomy.

And millidegrees are also quite common. But perhaps these are not prefixed in a principled way, as the unit names are a bit ad hoc (mdeg, mas, µas)? If they don't qualify as `Metric`, how would you suggest to handle these in practice? Define new units (`milliarcsecond`) rather than prefix them?

**Comment by dmcclean** [comment]
I think that defining explicit combination units in `NonSI` like `milliarcsecond` is probably the best approach, due to the standards issue and the less principled way in which those prefixes are applied?

**Comment by bjornbm** [comment]
I think I agree with you. Thanks.

**Comment by dmcclean** [comment]
Similar pseudo-metric units exist in other areas of US practice. For example, large wire sizes are specified in "kcmil" or thousands of circular mils, where a circular mil is the area of a circle 0.001" in diameter. Millions of circular mils are also occasionally used. I am about to define these units in a library I use for electrical work, but I would argue that they are more extreme examples of the same thing.

As such I am closing this one as we agree on the answer. I recommend creating a new feature request issue for adding the `milliarcsecond` etc units?
