### ISSUE TITLE
Get GHC 8.4 test working on Travis CI

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional#184]
See last few comments to #183. I took a quick look and [this looks relevant](https://bugs.launchpad.net/ubuntu/+source/ncurses/+bug/259139). I'm not familiar with Travis CI though (@dmcclean set it up for us) and don't have time to investigate more right now. Once complete we can undo 8f2e5db.

**Comment by dmcclean** [comment]
I also do not have time, at least this week, to relearn how Travis works and look into this. Also community practices on how to use travis for haskell projects seem to have changed a couple of times since we originally did it for this project.

**Comment by bjornbm** [comment]
Yes, I saw that our config is not quite in synch with the current stack docs on using Travis. I'm not putting a high priority on this for myself for the time being, and understanding that you are quite time constrained nowadays I don't expect that from you either.

**Comment by dmcclean** [comment]
Is there still an issue here or have previous changes to the travis script addressed it?

**Comment by dmcclean** [comment]
The latest Travis builds against LTS-12 (GHC 8.4) had successful doctest and hspec test suite runs. I will close this on that basis, if I am misunderstanding an ongoing issue please reopen.
