### ISSUE TITLE
So how do I use this?

### ISSUE THREAD

**Issue by Recruiter2** [bjornbm/dimensional#193]
Can I use this to solve dimensional equation?
How do I use it I'm new

here were I got 

Last login: Sun Sep 23 10:53:55 on console
wifi-de-tim:~ Timour$ import Numeric.Units.Dimensional.Prelude
-bash: import: command not found
wifi-de-tim:~ Timour$ Numeric.Units.Dimensional.Prelude
-bash: Numeric.Units.Dimensional.Prelude: command not found
wifi-de-tim:~ Timour$ gd Numeric.Units.Dimensional.Prelude
-bash: gd: command not found
wifi-de-tim:~ Timour$ gd dimensional-master
-bash: gd: command not found
wifi-de-tim:~ Timour$ cd dimensional-master
-bash: cd: dimensional-master: No such file or directory
wifi-de-tim:~ Timour$ git clone https://github.com/bjornbm/dimensional.git
Cloning into 'dimensional'...
remote: Enumerating objects: 4050, done.
remote: Total 4050 (delta 0), reused 0 (delta 0), pack-reused 4050
Receiving objects: 100% (4050/4050), 639.72 KiB | 1.15 MiB/s, done.
Resolving deltas: 100% (1717/1717), done.
wifi-de-tim:~ Timour$ cd Numeric.Units.Dimensional.Prelude
-bash: cd: Numeric.Units.Dimensional.Prelude: No such file or directory
wifi-de-tim:~ Timour$ import Numeric.Units.Dimensional.Prelude
-bash: import: command not found
wifi-de-tim:~ Timour$ cd dimensional
wifi-de-tim:dimensional Timour$ dimensional-master
-bash: dimensional-master: command not found
wifi-de-tim:dimensional Timour$ Numeric.Units.Dimensional.Prelude
-bash: Numeric.Units.Dimensional.Prelude: command not found
wifi-de-tim:dimensional Timour$ import Numeric.Units.Dimensional.Prelude
-bash: import: command not found
wifi-de-tim:dimensional Timour$

**Comment by bjornbm** [comment]
To use this library you will have to first install (and probably learn) the [Haskell language](https://haskell-lang.org).
