### ISSUE TITLE
Compiling with GHC 8.6.1 and testing with new-test

### ISSUE THREAD

**Issue by davean** [bjornbm/dimensional#194]
The attached patches fix dimensional to work on GHC 8.6.1 and test with new-test.
The only problem requiring fixing was that the handling of * at the type level changed.
To avoid CPP I used the default-extensions option with a guard in the cabal file. This left an issue with doctests which I handled by manually passing the language extension to the doctest function.

[0001-Fix-tests-on-cabal-new.patch.txt](https://github.com/bjornbm/dimensional/files/2477520/0001-Fix-tests-on-cabal-new.patch.txt)
[0002-Fix-for-GHC-8.6.1-s-StarIsType-change.patch.txt](https://github.com/bjornbm/dimensional/files/2477521/0002-Fix-for-GHC-8.6.1-s-StarIsType-change.patch.txt)

**Comment by peti** [comment]
Ping?

**Comment by bjornbm** [comment]
Thanks @davean for the patches. See #195. I don't have time to work on this until next week. Feel free to submit an updated patch to speed this up.

**Comment by bjornbm** [comment]
@davean was it necessary to change `*` to `Type` (from `Data.Kind`) in `Dynamic.hs` and `Internal.hs`? Importing `Data.Kind` breaks GHC < 8. Can you provide pointers to the GHC docs explaining if/why it was necessary?

**Comment by davean** [comment]
https://github.com/ghc-proposals/ghc-proposals/blob/05721788de9ab6538def68c3c2c9dec50c9f24a8/proposals/0020-no-type-in-type.rst

As of 8.6 XStarIsType is on by default and I believe the
compatibility window schedules to be the only option in GHC 8.8.

**Comment by bjornbm** [comment]
FYI I have merged this into master but cannot yet deploy to hackage due to https://github.com/haskell/hackage-server/issues/788.

**Comment by FranklinChen** [comment]
Is there still a problem with updating on Hackage?

**Comment by dmcclean** [comment]
Yes. (I just retried it.)

**Comment by bjornbm** [comment]
https://github.com/haskell/hackage-server/issues/788 has reportedly been fixed! @dmcclean will you be ready to upload after merging `log1p` et al?

**Comment by dmcclean** [comment]
Standby about 2 hours, busy with Christmas cleanup. Excellent news!

**Comment by dmcclean** [comment]
v1.2 uploaded to hackage!
(Putting finishing touches on v1.3 which includes the breaking change to non-breaking spaces and a few minor things.)
