### ISSUE TITLE
Add dimensionless wrappers for log1p and friends

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#203]
Since base-4.9 the `Floating` class has had `log1p`, `expm1`, `log1pexp`, and `log1mexp`.

We should likely add `Dimensionless` wrappers for these.

**Comment by bjornbm** [comment]
Looks OK to me. Do you know what the tradeoff is? Perhaps we should consider making these the “least effort” options? E.g.:

```
log = fmap Numeric.log1p
log_ = fmap Prelude.log
```

**Comment by dmcclean** [comment]
I think it's basically along these lines:
Pro: If you go looking for something from the `Floating` typeclass, there is a dimensional wrapper for it, so you have guidance as to what the proper dimensions are.
Con: Additional name consumption, and of some strange names.

I'm confused by the alternative you propose. `log1p = log . (+1)` but with a possibly more precise result when the argument is very small.

```
μ> Numeric.log1p 2
1.0986122886681098
μ> Prelude.log 3
1.0986122886681098
```

**Comment by bjornbm** [comment]
Ah, sorry, I misread the docs and purpose of `log1p` (et al). I think this change is good. 👍
