### ISSUE TITLE
Metadata update from Hackage?

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional#207]
@hvr updated the metadata for dimensional-1.3 on Hackage on 2019-02-09  (see https://hackage.haskell.org/package/dimensional-1.3/revisions/):

* Changed the library component's library dependency on 'base' from `>=4.7 && <5` to `>=4.9 && <5`
* Changed the benchmark 'simple' component's library dependency on 'base' from `-any` to `<4.7`

The first change makes sense since we dropped support for GHC < 8.0.1, but I do not understand the reason for the second change? Email sent to @hvr to try to clarify (but feel free to answer here instead!).

**Comment by bjornbm** [comment]
Once this is sorted out we should re-enable dimensional in Stackage. See https://github.com/commercialhaskell/stackage/pull/4275. Currently the checklist items fail due to the benchmark constraint:

> Resolver 'nightly-2019-03-20' does not have a matching compiler to build some or all of your package(s).
> ghc-8.6.4 cannot be used for these packages:
>     - dimensional
> base version 4.12.0.0 found
>     - dimensional requires <4.7 && >=4.9 && <5

**Comment by mihaimaruseac** [comment]
We can also enable the package on Stackage with benchmarks disabled, if needed

**Comment by mihaimaruseac** [comment]
Don't want to put words/actions to @hvr, but I think the change in base is because `base` should always have upper bounds, everywhere? I recall there being a consensus both on Stackage and Hackage to have that, but I might be wrong.

**Comment by bjornbm** [comment]
Thanks @mihaimaruseac. For enabling with benchmarks disabled (which seems like a reasonable approach), it isn't quite clear to me from the comments `build-constraints.yaml` if dimensional should go into `expected-benchmark-failures:` or `skipped-benchmarks:`?

**Comment by mihaimaruseac** [comment]
`skipped-benchmarks` since we don't want to compile them

**Comment by bjornbm** [comment]
@hvr replied to my email made [another revision](https://hackage.haskell.org/package/dimensional-1.3/revisions/).

* Changed the benchmark 'simple' component's library dependency on 'base' from `<4.7` to `<5`.

I've updated our cabal file to be consistent with @hvr's revisions.

Thanks @hvr and @mihaimaruseac!
