### ISSUE TITLE
Get Travis (or other service) building dimensional again

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional#217]
Travis has stopped building dimensional:

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

See https://docs.travis-ci.com/user/migrate/open-source-repository-migration (and maybe https://docs.travis-ci.com/user/tutorial/). Hopefully migrating will be straight-forward.

**Comment by bjornbm** [comment]
OK, so I had to jump through some hoops and create an account on travis-ci.com. Free plan. Unclear how long it will be working… seems I will have eventually to request open source credits or some other bullshit. Annoying. Would be happy to move elsewhere.

**Comment by konsumlamm** [comment]
In my experience GitHub Actions work quite well, I could put together a PR for switching to that if you like.

**Comment by bjornbm** [comment]
Sounds great to me if you have the time @konsumlamm!
