### ISSUE TITLE
Add `decade` and `millennium` units?

### ISSUE THREAD

**Issue by konsumlamm** [bjornbm/dimensional#219]
`Numeric.Units.Dimensional.NonSI` currently has a `century` unit, meaning 100 years. Decade and millennium are two other common units, meaning 10 and 1000 years, respectively.

**Comment by bjornbm** [comment]
This is an example of where the adding of units has been more need-driven than systematic. `century` is in there because many astronomical calculations I've used are based around (Julian) centuries. I have no objections in principle to adding `decade` and `millennium`.
