### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by LaurentRDC** [bjornbm/dimensional#227]
Hello,

Following #224 , would it be possible to create a new release?

I'm also happy to serve as maintainer here and on Hackage (username: LaurentRDC) to help.

**Comment by bjornbm** [comment]
Yes, of course. I’ll do it tonight or tomorrow. I appreciate the maintainer
offer and will set it up, too!

**Comment by LaurentRDC** [comment]
dimensional 1.6 is up; thanks!
