### ISSUE TITLE
Use type families in Quantities?

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional#32]
Type families have opened up the possibility of rewriting the `Dimension`s using type families. Examples:

``` haskell
type DArea = DLength * DLength
type Area  = Quantity DArea

type DVolume = DLength ^ Pos3
type Volume  = Quantity DVolume
```

I feel this could be instructive, but perhaps detrimental to the searchability for suitable `Dimension`s, so I'm not sure if it is a good idea or not.

Either way I don't want to make this kind of change at this time as it would severely reduce the portability to/from dimensional-fd. Perhaps when dimensional-fd has been deprecated in favor of dimensional-dk and I stop maintaining it.

**Comment by dmcclean** [comment]
I feel that the search thing outweighs the clarity on this. Unfortunately I can't think of any tooling that would allow us to have both. We could have documentation explaining the definitions in more familiar terms but would run the risk of making mistakes in writing it.

The only thing I can think of is that there might be some utility to a term-level form of "the search thing", i.e. `dimensionNames :: Dimension' -> [String]`, but without getting in to TH it would be quite redundant to maintain the required `Map`, even without considering internationalization.

I vote to close.

**Comment by dmcclean** [comment]
See https://ghc.haskell.org/trac/ghc/ticket/10391 for a possible ultra-long-term improvement.
