### ISSUE TITLE
Retire variants?

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional#40]
#2 started out being mostly about removing the distinction between quantities and units. I was reluctant then, saying:

> Separating units and quantities was a very conscious decision, and one that I am quite happy with and feel has worked quite well in practice (YMMV). Converting quantities to values is performed, by necessity, very close to [NIST guidelines](http://physics.nist.gov/Pubs/SP811/sec07.html) (see 7.1 and 7.8) and I think this is a good thing.

Now, in light of e.g. #38, I'm reconsidering. Perhaps the added complexity of separating 'Quantity' and 'Unit' is not worth the extra complexity (`Variant` phantom type) and occasionally convoluted workarounds (e.g. `Prelude.` uses) that it can cause.

Relaxing would allow some ugly stuff:

```
x = kilo (meter + mile)
y = second * x
```

But even the current design isn't perfect with regards to NIST, allowing, e.g.:

```
u = kilo (kilo (meter / second))
```

so I'm not sure it is worth defending.

I would like to hear if you, Doug, have had any more thoughts on this topic. I know that you have actually gone even further with the distinction in the named-units branch, and imagine the impact would be treating everything as a unit (i.e. keep tracking the unit name) until multiplying with a `Num` (e.g. with `(*~)`).

**Comment by dmcclean** [comment]
Closing this as adequately and more comprehensively discussed under #46 and #48.
