### ISSUE TITLE
Dimension of action?

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#80]
In experimental's Codata module we had:

````
-- Alias this dimension as DAction? Seems rarely used?

planckConstant :: (Fractional a) => AngularMomentum a
planckConstant = 6.62606957e-34 *~ (joule * second)
````

This definition doesn't compile under the angular branch, because of the missing radians.

Seems the correct solution would be to add `DAction` and `Action` to the `Quantities` module? Just checking because I've never been really clear on what this constant is about, and the wikipedia page explaing action is ... perplexing.

**Comment by dmcclean** [comment]
I was thinking of voting :-1: on this one, because `Action` seemed like a useful name to steal for such an obscure thing, but now I'm not sure because Hoogle doesn't actually show much use of it.

For now I changed the type signature for `planckConstant` to explicitly list the dimension instead of using a name so that it compiles against the angular branch.

**Comment by bjornbm** [comment]
My first question here is: are we certain that the dimension should not be the same as for angular momentum? I.e., that the unit should be J.s.rad? This would be consistent with h-bar being J.s and h = 2 pi h-bar. (h-bar times one revolution).




I wish I had the time to find (and work through) good examples of h and h-bar usage to answer this.




I wouldn't worry too much about `Action` I think if there were no clashes with major libraries. And I imagine any user of dimensional will have to learn to import qualified/hiding anyway sooner or later anyway. But would we benefit from an experimental(?) Quantities module too that is not part of the prelude?

**Comment by dmcclean** [comment]
Good question but I have no idea what the answer is. :)

**Comment by dmcclean** [comment]
Not claiming expertise on this, but it seems like `planckConstant` does have the action dimension and not the angular momentum dimension.

Otherwise you don't get E = h c / λ to balance.

Reduced planck constant does have an additional rad^-1.
