### ISSUE TITLE
Alias DImpulse as DMomentum?

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional#90]
AFAICS we don't have a dimension alias for translational momentum, only for angular momentum. It's the same as the one currently called `DImpulse`.

Can I add an alias or am I missing a reason why this is a bad idea?

**Comment by bjornbm** [comment]
OK with me. Probably isn't in because it isn't in the NIST guide and we haven't needed it until now (somewhat surprising!). Either `DMomentum` or `DLinearMomentum`, probably the former/shorter one unless you can think of any ambiguity with it.
