### ISSUE TITLE
Hackage and Stackage support

### ISSUE THREAD

**Issue by varosi** [bjornbm/dimensional#91]

**Comment by dmcclean** [comment]
Working on getting on hackage this week.

I confess to not understanding stack or what it is meant to do. Could you clarify what stackage support looks like?

**Comment by varosi** [comment]
Stack is the new generation Haskell build platform based on cabal-install and supported by FP Complete:
https://github.com/commercialhaskell/stack

It's very easy and guaranteed installation using stack. It is just an executable that could download right version of GHC and cabal and use them to install dimensional-dk linking it against stable version of Hackage libraries (Stackage). All libraries on Stackage are guaranteed to build on multiple OSes and work with each other. So you don't need to fight with Cabal Hell.

**Comment by varosi** [comment]
By Stackage support I mean this library to be published there:
http://www.stackage.org

But it first need to be published in Hackage to be visible.

**Comment by varosi** [comment]
"dimensional" is already there

**Comment by dmcclean** [comment]
We're now on Hackage as [`dimensional-1.0.0.0`](http://hackage.haskell.org/package/dimensional). If I understand correctly, this will take us to Stackage in due course because the `dimensional` name is already on their list. Please re-open if this is incorrect or we need to do something else. Thanks!

**Comment by varosi** [comment]
Will dimensional-dk be on Hackage soon?

2015-10-31 4:17 GMT+02:00 Douglas McClean notifications@github.com:

**Comment by varosi** [comment]
I see only "dimensional" library without "-dk" suffix.

2015-11-02 12:32 GMT+02:00 eng. Vassil Ognyanov Keremidchiev <
varosi@gmail.com>:

**Comment by dmcclean** [comment]
We've elected to release the efforts that we had been developing as `dimensional-dk` as a new major version of `dimensional`, since it solves the same problem but in a better way. If you still need the classical one you can constrain the library that needs it to use a version `< 1`.

**Comment by varosi** [comment]
Ah, okay, great!

Thanks!

2015-11-02 16:52 GMT+02:00 Douglas McClean notifications@github.com:

> We've elected to release the efforts that we had been developing as
> dimensional-dk as a new major version of dimensional, since it solves the
> same problem but in a better way.
