### ISSUE TITLE
Haddock link issues

### ISSUE THREAD

**Issue by ivan-m** [bjornbm/dimensional#93]
It seems that every link to `Pos1` of the documentations on Hackage tries to link to `c:/Users/Doug/AppData/Local/GitHub/PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad/package/numtype-dk-0.5/docs/Numeric-NumType-DK-Integers.html#v:Pos1`; the same goes for `Zero`, etc.

**Comment by dmcclean** [comment]
Thanks for the report Ivan. Evidently I stuffed up building the documentation to upload to Hackage. I will look in to fixing it ASAP.

**Comment by dmcclean** [comment]
I believe the issue may be that I built the documentation in a cabal sandbox that had an add-source dependency on `numtype-dk` left over from when that was in flux. I've trashed that sandbox and am in the process of making a new one, the docs from that should have links to the correct places.

**Comment by ivan-m** [comment]
Any particular reason for not letting Hackage build the documentation rather than building it yourself?

**Comment by dmcclean** [comment]
Do you know how long it usually takes? I waited about 12 hours and then took the fact that it hadn't happened as a sign that it wasn't going to, and started researching how to upload them myself. It could be that I did something else wrong that prevented them from building, but it said no build reports were available yet either.

**Comment by dmcclean** [comment]
I can't fix this for the life of me. All the scripts I can find for making it happen are very unhappy on windows for reasons I don't quite understand.

**Comment by ivan-m** [comment]
I believe it batches them daily or something.

Otherwise, I think Neil Mitchell uses Windows, and he has some custom scripts [here](http://neilmitchell.blogspot.com.au/2014/10/fixing-haddock-docs-on-hackage.html).

**Comment by dmcclean** [comment]
I've given hackage a few days to build it and it doesn't seem to have tried, at least it still says no build reports are available.

I'll see what I can do with Neil's scripts. Thanks.

**Comment by ivan-m** [comment]
I think that once you've uploaded documentation, then Hackage doesn't bother trying to build it.

That said, the [latest version](http://hackage.haskell.org/package/postgresql-simple-0.5.1.0) of postgresql-simple has been on Hackage for a few weeks and hasn't had any build yet either, so maybe something is broken on Hackage and no docs are being built :s

**Comment by dmcclean** [comment]
The button to delete the documentation I had uploaded claimed that it would trigger a rebuild.
It does appear that perhaps something is wrong with this feature of Hackage.
I wish I could figure out how to generate them myself with the correct links. I've tried a few people's scripts and am having trouble. (Curse of Windows.) One of them generated the correct links but then couldn't compress them properly for some reason I didn't understand. I will try again tonight after work.

**Comment by dmcclean** [comment]
And eventually it did trigger a documentation build, but that failed due to what appears to be an issue with `vector`. Log at http://hackage.haskell.org/package/dimensional-1.0.0.0/reports/1. Snipping relevant portion:

```
[13 of 21] Compiling Data.Vector.Primitive.Mutable ( Data/Vector/Primitive/Mutable.hs, dist/build/Data/Vector/Primitive/Mutable.o )

Data/Vector/Primitive/Mutable.hs:53:1:
    Bad interface file: /home/builder/hackage-server/build-cache/tmp-install/lib/x86_64-linux-ghc-7.10.2/primitive-0.6.1.0-5Jnw7oEuYtM9dmKXelGXVb/Data/Primitive/ByteArray.hi
        /home/builder/hackage-server/build-cache/tmp-install/lib/x86_64-linux-ghc-7.10.2/primitive-0.6.1.0-5Jnw7oEuYtM9dmKXelGXVb/Data/Primitive/ByteArray.hi: openBinaryFile: does not exist (No such file or directory)

Data/Vector/Primitive/Mutable.hs:54:1:
    Bad interface file: /home/builder/hackage-server/build-cache/tmp-install/lib/x86_64-linux-ghc-7.10.2/primitive-0.6.1.0-5Jnw7oEuYtM9dmKXelGXVb/Data/Primitive.hi
        /home/builder/hackage-server/build-cache/tmp-install/lib/x86_64-linux-ghc-7.10.2/primitive-0.6.1.0-5Jnw7oEuYtM9dmKXelGXVb/Data/Primitive.hi: openBinaryFile: does not exist (No such file or directory)
Failed to install vector-0.11.0.0
```

I don't understand what this means, so I guess I'll take another swing at building them myself on windows.

**Comment by dmcclean** [comment]
Hackage built the docs for the new version 1.0.1.0 almost immediately and successfully.

Let us proclaim the mystery of hackage.
